// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"vi": &dictionary{index: viIndex, data: viData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("zh")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"🤖️：%s": 1,
	"🤖️：消息机器人摆烂了，请稍后再试～\n错误信息: %v": 2,
	"🤖️：语音转换失败，请稍后再试～\n错误信息: %v":   0,
}

var viIndex = []uint32{ // 4 elements
	0x00000000, 0x00000065, 0x00000065, 0x00000065,
} // Size: 40 bytes

const viData string = "" + // Size: 101 bytes
	"\x02Chuyển đổi giọng nói không thành công, vui lòng thử lại sau~Thông bá" +
	"o lỗi: %[1]v"

var zhIndex = []uint32{ // 4 elements
	0x00000000, 0x00000046, 0x00000056, 0x000000a2,
} // Size: 40 bytes

const zhData string = "" + // Size: 162 bytes
	"\x02🤖️：语音转换失败，请稍后再试～\x0a错误信息: %[1]v\x02🤖️：%[1]s\x02🤖️：消息机器人摆烂了，请稍后再试～" +
	"\x0a错误信息: %[1]v"

	// Total table size 343 bytes (0KiB); checksum: EF48A9F
