// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"vi": &dictionary{index: viIndex, data: viData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("zh")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s.png":       4,
	"可用额度: %.2f$":  9,
	"已用额度: %.2f$":  8,
	"总额度: %.2f$":   7,
	"有效期: %s - %s": 10,
	"🤖️：%s":        2,
	"🤖️：图片下载失败，请稍后再试～\n 错误信息: %v":  3,
	"🤖️：图片生成失败，请稍后再试～\n错误信息: %v":   6,
	"🤖️：无法解析图片，请发送原图并尝试重新操作～":      5,
	"🤖️：消息机器人摆烂了，请稍后再试～\n错误信息: %v": 1,
	"🤖️：语音转换失败，请稍后再试～\n错误信息: %v":   0,
}

var viIndex = []uint32{ // 12 elements
	0x00000000, 0x00000066, 0x000000ae, 0x000000ae,
	0x000000ae, 0x000000ae, 0x000000ae, 0x000000ae,
	0x000000ae, 0x000000ae, 0x000000ae, 0x000000ae,
} // Size: 72 bytes

const viData string = "" + // Size: 174 bytes
	"\x02Chuyển đổi giọng nói không thành công, vui lòng thử lại sau~\x0aThôn" +
	"g báo lỗi: %[1]v\x02🤖️：Robot nhắn tin bị hỏng\x0avui lòng thử lại sau: %" +
	"[1]v"

var zhIndex = []uint32{ // 12 elements
	0x00000000, 0x00000046, 0x00000092, 0x000000a2,
	0x000000e9, 0x000000f3, 0x0000013a, 0x00000180,
	0x00000194, 0x000001ab, 0x000001c2, 0x000001db,
} // Size: 72 bytes

const zhData string = "" + // Size: 475 bytes
	"\x02🤖️：语音转换失败，请稍后再试～\x0a错误信息: %[1]v\x02🤖️：消息机器人摆烂了，请稍后再试～\x0a错误信息: %[1]v" +
	"\x02🤖️：%[1]s\x02🤖️：图片下载失败，请稍后再试～\x0a 错误信息: %[1]v\x02%[1]s.png\x02🤖️：无法解析" +
	"图片，请发送原图并尝试重新操作～\x02🤖️：图片生成失败，请稍后再试～\x0a错误信息: %[1]v\x02总额度: %.2[1]f$" +
	"\x02已用额度: %.2[1]f$\x02可用额度: %.2[1]f$\x02有效期: %[1]s - %[2]s"

	// Total table size 793 bytes (0KiB); checksum: FED2695E
